package ru.stqa.pft.webtest.tests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;

public final class EditProfileTest extends TestBase {

  @Test
  public void testEditProfile() throws InterruptedException {
    app.getAuthorizationHelper().authorization(By.name("submit"));
    app.getPathHelper().pathSelection();
    app.getEditionHelper(By.id("user_address_attributes_county"), "Испания").editSurname(By.id("user_surname"), By.id("user_firstname"), "Dzhanaev");
    app.getEditionHelper(By.id("user_address_attributes_county"), "Испания").editPhone(By.id("user_phone"), "89992450000");
    app.finishEdition();
  }

}
