package ru.stqa.pft.webtest.tests;// Generated by Selenium IDE

import org.junit.Test;
public final class EditProfileTest extends TestBase {

  @Test
  public void testEditProfile() throws InterruptedException {
    app.authorization();
    app.pathSelection();
    app.editSurname();
    app.editPhone();
    //editBirthDate();
    //selectLicenceperiod();
    app.finishEdition();
  }

}
