package ru.stqa.pft.webtest;// Generated by Selenium IDE

import org.junit.Test;
public final class EditProfileTest extends TestBase {

  @Test
  public void testEditProfile() throws InterruptedException {
    authorization();
    pathSelection();
    editSurname();
    editPhone();
    //editBirthDate();
    //selectLicenceperiod();
    finishEdition();
  }

}
