package ru.stqa.pft.webtest;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class WebTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    browserOpen();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  private void browserOpen() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\na_dzhanaev\\Desktop\\chromedriver.exe");
    driver = new ChromeDriver();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void webTest() {
    goToInsurancePage();
    driver.manage().window().setSize(new Dimension(847, 649));
    goToRegisterPage(By.linkText("Register"));
    fillingOutTheRegistrationForm(new RegistrationForm("Nikolay", "Nikolay", "8999999999"));
    authAfterRegistration();
  }

  private void authAfterRegistration() {
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("djanai9219@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Qwerty1");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.cssSelector("h4")).click();
  }

  private void fillingOutTheRegistrationForm(RegistrationForm registrationForm) {
    driver.findElement(By.id("user_firstname")).sendKeys(registrationForm.firstname());
    driver.findElement(By.id("user_surname")).click();
    driver.findElement(By.id("user_surname")).sendKeys(registrationForm.surname());
    driver.findElement(By.id("user_phone")).click();
    driver.findElement(By.id("user_phone")).sendKeys(registrationForm.phoneNumber());
    driver.findElement(By.id("user_dateofbirth_3i")).click();
    {
      WebElement dropdown = driver.findElement(By.id("user_dateofbirth_3i"));
      dropdown.findElement(By.xpath("//option[. = '20']")).click();
    }
    driver.findElement(By.id("user_dateofbirth_1i")).click();
    {
      WebElement dropdown = driver.findElement(By.id("user_dateofbirth_1i"));
      dropdown.findElement(By.xpath("//option[. = '1950']")).click();
    }
    driver.findElement(By.id("user_address_attributes_street")).click();
    driver.findElement(By.id("user_address_attributes_street")).sendKeys("street");
    driver.findElement(By.id("user_address_attributes_city")).click();
    driver.findElement(By.id("user_address_attributes_city")).sendKeys("city");
    driver.findElement(By.id("user_address_attributes_county")).click();
    driver.findElement(By.id("user_address_attributes_county")).sendKeys("country");
    driver.findElement(By.id("user_address_attributes_postcode")).click();
    driver.findElement(By.id("user_address_attributes_postcode")).sendKeys("sy24 be");
    driver.findElement(By.id("user_user_detail_attributes_email")).click();
    driver.findElement(By.id("user_user_detail_attributes_email")).sendKeys("djanai9219@gmail.com");
    driver.findElement(By.cssSelector(".newadd:nth-child(6) > div:nth-child(2)")).click();
    driver.findElement(By.id("user_user_detail_attributes_password")).click();
    driver.findElement(By.id("user_user_detail_attributes_password")).sendKeys("Qwerty1");
    driver.findElement(By.id("user_user_detail_attributes_password_confirmation")).click();
    driver.findElement(By.id("user_user_detail_attributes_password_confirmation")).sendKeys("Qwerty1");
    driver.findElement(By.name("submit")).click();
  }

  private void goToRegisterPage(By register) {
    driver.findElement(register).click();
  }

  private void goToInsurancePage() {
    driver.get("http://demo.guru99.com/insurance/v1/index.php");
  }

  public Map<String, Object> getVars() {
    return vars;
  }

  public void setVars(Map<String, Object> vars) {
    this.vars = vars;
  }
}
